title: Helios'Blog   # your title
author: Helios # your name
description: Yep! Just for fun # your description
avatar: /images/avatar.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 4
paginate_path: "/page:num/"
gems: [jekyll-paginate]

# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
